services:
  api:
    build: .
    container_name: raijai-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_RAIJAI
    volumes:
      - .:/app:cached
    working_dir: /app
    command: ["go", "run", "main.go"]
